"use client";
import { useEffect, useState } from "react";
import { clients as demoClients } from "../../lib/demo-data";
import { ClientCard } from "../../components/client-card";
import { Shell } from "../../components/shell";
import { createClient, fetchClients } from "../../lib/supabase-data";
import { ClientDetail } from "../../lib/types";

export default function ClientsPage() { const [clients, setClients] = useState<ClientDetail[]>(demoClients); const [message, setMessage] = useState("Loading connected clients…"); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); useEffect(() => { fetchClients().then((rows) => { setClients(rows); setMessage(rows.length ? "Connected to Supabase" : "No clients added yet"); }).catch(() => setMessage("Showing demo clients until Supabase access is configured.")); }, []); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { await createClient({ name: String(form.get("name")), industry: String(form.get("industry")), location: String(form.get("location")), website: String(form.get("website")), health_score: Number(form.get("health_score") || 0) }); setShowForm(false); setMessage("Client added successfully"); const rows = await fetchClients(); setClients(rows); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add client."); } finally { setBusy(false); } } return <Shell active="Clients"><div className="page-heading"><div><p className="eyebrow">Workspace</p><h1>Clients</h1><p className="lede">A clear, current view of every account you manage.</p><small className="updated">{message}</small></div><button className="button button-dark" onClick={() => setShowForm(!showForm)}>+ Add client</button></div>{showForm && <form className="detail-card client-form" onSubmit={submit}><p className="eyebrow">New account</p><h2>Add a client</h2><div className="form-grid"><input name="name" placeholder="Business name" required /><input name="industry" placeholder="Industry" required /><input name="location" placeholder="Location" /><input name="website" placeholder="Website" /><input name="health_score" type="number" min="0" max="100" placeholder="Health score" /></div>{error && <p className="login-notice error">{error}</p>}<button className="button button-dark" disabled={busy}>{busy ? "Saving…" : "Save client"}</button></form>}<section className="client-grid client-grid-wide">{clients.map((client) => <ClientCard client={client} key={client.id} />)}</section></Shell>; }
