"use client";
import { useEffect, useState } from "react";
import { ClientPerson } from "../lib/types";
import { createClientPerson, deleteClientPerson, fetchClientPeople, updateClientPerson } from "../lib/supabase-data";

const blank = { name: "", role: "", email: "", phone: "", notes: "" };
export function PeoplePanel({ clientId }: { clientId: string }) {
  const [people, setPeople] = useState<ClientPerson[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<ClientPerson | null>(null); const [open, setOpen] = useState(false); const [status, setStatus] = useState("Loading people…"); const [busy, setBusy] = useState(false);
  const load = () => fetchClientPeople(clientId).then((rows) => { setPeople(rows); setStatus(rows.length ? "" : "No people added yet."); }).catch((e) => setStatus(e instanceof Error ? e.message : "Unable to load people."));
  useEffect(() => { load(); }, [clientId]);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); try { if (editing) await updateClientPerson(editing.id, form); else await createClientPerson({ ...form, client_id: clientId }); setForm(blank); setEditing(null); setOpen(false); await load(); } catch (e) { setStatus(e instanceof Error ? e.message : "Unable to save person."); } finally { setBusy(false); } }
  function edit(person: ClientPerson) { setEditing(person); setForm({ name: person.name, role: person.role, email: person.email, phone: person.phone, notes: person.notes }); setOpen(true); }
  async function remove(id: string) { if (!window.confirm("Remove this person?")) return; await deleteClientPerson(id); await load(); }
  return <section className="detail-card people-panel"><div className="section-heading"><div><p className="eyebrow">Contacts</p><h2>People at this company</h2></div><button className="button button-dark" onClick={() => { setEditing(null); setForm(blank); setOpen(!open); }}>{open ? "Close" : "+ Add person"}</button></div>{open && <form className="people-form" onSubmit={save}><div className="form-grid"><input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Role or title" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} /><input type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input type="tel" placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><textarea placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><button className="button button-dark" disabled={busy}>{busy ? "Saving…" : editing ? "Save person" : "Add person"}</button></form>} {status && <p className="muted people-status">{status}</p>}<div className="people-grid">{people.map((person) => <article className="person-card" key={person.id}><span className="client-avatar">{person.name.split(/\s+/).map((p) => p[0]).join("").slice(0, 2).toUpperCase()}</span><div><h3>{person.name}</h3><p>{person.role || "Company contact"}</p>{person.email && <a href={`mailto:${person.email}`}>{person.email}</a>}{person.phone && <a href={`tel:${person.phone}`}>{person.phone}</a>}{person.notes && <small>{person.notes}</small>}</div><div className="person-actions"><button className="text-link" onClick={() => edit(person)}>Edit</button><button className="text-link danger-link" onClick={() => remove(person.id)}>Remove</button></div></article>)}</div></section>;
}
