import { ClientDetail, ClientSummary, Activity } from "./types";

export const clients: ClientDetail[] = [
  { id:"hvac-ministries", name:"HVAC Ministries", initials:"HM", industry:"HVAC Services", location:"Dallas, TX", health:92, status:"healthy", website:"hvacministries.com", owner:"Joseph Torres", services:["SEO Strategy","Local Search","Website Care"], lastUpdated:"12 min ago", overview:"A high-intent local service brand focused on growing qualified calls and visibility across the Dallas–Fort Worth market.", metrics:[{label:"Organic traffic",value:"18.4K",change:"18%",trend:"up"},{label:"Google clicks",value:"4,280",change:"24%",trend:"up"},{label:"Conversions",value:"186",change:"12%",trend:"up"}], traffic:[{month:"Mar",value:42},{month:"Apr",value:50},{month:"May",value:46},{month:"Jun",value:64},{month:"Jul",value:61},{month:"Aug",value:78}], opportunities:["Build a dedicated AC repair page","Improve map pack coverage in Plano","Refresh 6 pages losing impressions"] },
  { id:"taqueria-market", name:"Taqueria Market", initials:"TM", industry:"Restaurant", location:"Austin, TX", health:87, status:"watch", website:"taqueriamarket.com", owner:"Joseph Torres", services:["Local Search","Reviews","Content"], lastUpdated:"38 min ago", overview:"A neighborhood restaurant building a stronger local presence through discovery, reviews, and seasonal content.", metrics:[{label:"Organic traffic",value:"9.8K",change:"11%",trend:"up"},{label:"Reviews",value:"4.6 ★",change:"0.2",trend:"up"},{label:"Profile actions",value:"2,140",change:"8%",trend:"up"}], traffic:[{month:"Mar",value:48},{month:"Apr",value:45},{month:"May",value:54},{month:"Jun",value:57},{month:"Jul",value:68},{month:"Aug",value:72}], opportunities:["Respond to 8 unanswered reviews","Add weekend menu schema","Publish the September seasonal page"] },
  { id:"torres-and-co", name:"Torres & Co.", initials:"TC", industry:"Professional Services", location:"Nationwide", health:94, status:"healthy", website:"torresandco.com", owner:"Joseph Torres", services:["Strategy","Analytics","Web Operations"], lastUpdated:"1 hr ago", overview:"The agency’s own growth engine: a clear view of performance, pipeline, and the systems powering client delivery.", metrics:[{label:"Search visibility",value:"71%",change:"17%",trend:"up"},{label:"Qualified leads",value:"42",change:"31%",trend:"up"},{label:"Site health",value:"94",change:"4%",trend:"up"}], traffic:[{month:"Mar",value:38},{month:"Apr",value:49},{month:"May",value:51},{month:"Jun",value:59},{month:"Jul",value:67},{month:"Aug",value:81}], opportunities:["Create a case studies hub","Connect lead source tracking","Prioritize Q4 content themes"] }
];

export const activities: Activity[] = [
  {id:"a1",clientId:"hvac-ministries",title:"SEO opportunity found",detail:"AC repair page has rising impressions",time:"12 min ago",type:"insight"},
  {id:"a2",clientId:"taqueria-market",title:"Monthly report ready",detail:"August performance summary is ready to review",time:"38 min ago",type:"report"},
  {id:"a3",clientId:"torres-and-co",title:"Visibility milestone",detail:"Search visibility crossed 70% this week",time:"1 hr ago",type:"insight"},
  {id:"a4",clientId:"hvac-ministries",title:"Needs attention",detail:"3 pages have dropped in average position",time:"2 hrs ago",type:"alert"}
];

export function getClient(id: string) { return clients.find((client) => client.id === id); }
