import { notFound } from "next/navigation";
import Link from "next/link";
import { getClient } from "../../../lib/demo-data";
import { Shell } from "../../../components/shell";
import { clients } from "../../../lib/demo-data";

export function generateStaticParams() { return clients.map((client) => ({ id: client.id })); }

export default async function ClientPage({ params }: { params: { id: string } }) { const client = getClient(params.id); if (!client) notFound(); return <Shell active="Clients"><Link className="back-link" href="/clients">← Back to clients</Link><div className="client-hero"><div><p className="eyebrow">Client workspace</p><h1>{client.name}</h1><p className="lede">{client.industry} · {client.location} · {client.website}</p></div><span className={`status-badge ${client.status}`}>{client.status === "healthy" ? "● Healthy" : "● Watch"}</span></div><div className="detail-grid"><section className="detail-main"><div className="detail-card"><div className="section-heading"><div><p className="eyebrow">Performance snapshot</p><h2>What’s moving</h2></div><span className="updated">Updated {client.lastUpdated}</span></div><div className="metric-grid">{client.metrics.map((metric) => <div className="metric" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small className="positive">↑ {metric.change}</small></div>)}</div><div className="chart"><div className="chart-label"><span>Organic performance</span><strong>Last 6 months</strong></div><div className="bars">{client.traffic.map((point) => <div className="bar-wrap" key={point.month}><div className="bar" style={{height:`${point.value}%`}} title={`${point.value} index`} /><span>{point.month}</span></div>)}</div></div></div><div className="detail-card"><p className="eyebrow">Next best actions</p><h2>Opportunities</h2><div className="opportunity-list">{client.opportunities.map((opportunity, index) => <div className="opportunity" key={opportunity}><span>0{index+1}</span><p>{opportunity}</p><button aria-label={`Open ${opportunity}`}>→</button></div>)}</div></div></section><aside className="detail-side"><div className="detail-card"><p className="eyebrow">Account</p><h2>About {client.name}</h2><p className="body-copy">{client.overview}</p><div className="owner"><span className="avatar">JT</span><div><strong>{client.owner}</strong><small>Account owner</small></div></div></div><div className="detail-card"><p className="eyebrow">Contact</p><h2>Business details</h2><div className="contact-list"><a className="contact-row" href={`mailto:${client.email ?? ""}`}><span>✉</span><div><small>Email</small><strong>{client.email ?? "Not provided"}</strong></div></a><a className="contact-row" href={`tel:${client.phone ?? ""}`}><span>⌕</span><div><small>Phone</small><strong>{client.phone ?? "Not provided"}</strong></div></a><a className="contact-row" href={client.website.startsWith("http") ? client.website : `https://${client.website}`} target="_blank" rel="noreferrer"><span>↗</span><div><small>Website</small><strong>{client.website}</strong></div></a></div></div><div className="detail-card"><p className="eyebrow">Active services</p>{client.services.map((service) => <div className="service" key={service}><span>✓</span>{service}</div>)}</div></aside></div></Shell>; }
